config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :todos
  resources :users
  get "/", to: "home#index"
  get "/signin", to: "sessions#new", as: :new_session
  post "/signin", to: "sessions#create", as: :session
  delete "/signout", to: "sessions#destroy", as: :delete_session
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :todo_text, presence: true
  validates :todo_text, length: { minimum: 2 }
  validates :due_date, presence: true
  belongs_to :users, optional: true

  def to_pleasant_string
    status = completed ? "[X]" : "[]"
    "#{id} #{status} #{todo_text} #{due_date}"
  end

  def self.due_today
    where(due_date: Date.today)
  end

  def self.due_later
    where("due_date > ?", Date.today)
  end

  def self.overdue
    where("due_date < ? ", Date.today)
  end

  def self.completed?
    where(completed: true)
  end

  def completed?
    completed
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :todos
  has_secure_password

  def to_pleasant_string
    "#{id} #{first_name} #{email}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :ensure_signin

  def ensure_signin
    unless current_user
      redirect_to "/"
    end
  end

  def current_user
    return @current_user if @current_user
    current_user_id = session[:current_user_id]
    if current_user_id
      @current_user = User.find(current_user_id)
    else
      nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :ensure_signin

  def index
    if current_user
      redirect_to todos_path
    else
      render "index"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_signin

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:current_user_id] = user.id
      redirect_to "/"
    else
      flash[:error] = "Invalid Login Attempt"
      redirect_to new_session_path
    end
  end

  def destroy
    session[:current_user_id] = nil
    @current_user = nil
    redirect_to "/"
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todo = Todo.where(user_id: current_user.id)
    render "index"
  end

  def create
    new_todo = Todo.new(todo_text: params[:todo_text],
                        due_date: params[:due_date],
                        completed: false,
                        user_id: current_user.id)
    if new_todo.save
      redirect_to todos_path
    else
      flash[:error] = new_todo.errors.full_messages.join(", ")
      redirect_to todos_path
    end
  end

  def update
    todo = Todo.where(user_id: current_user.id).find(params[:id])
    flag = (params[:completed] == true || "on") ? true : false
    todo.completed = flag
    todo.save
    redirect_to todos_path
  end

  def destroy
    id = params[:id]
    todo = Todo.where(user_id: current_user.id).find(id)
    print todo
    todo.destroy
    redirect_to todos_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_signin

  def new
  end

  def index
    render "signup"
  end

  def create
    user = User.create!(first_name: params[:first_name],
                        last_name: params[:last_name],
                        email: params[:email],
                        password: params[:password])
    session[:current_user_id] = user.id
    redirect_to "/"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<p class="Signup-header">My Todo Manager</p>
<p class="Home-message">You have to be signed-in to start managing your todos</p>
<div class="Home-section">
<span>New to the Todo Manager</span>
<%= link_to "Sign-up here", users_path %>
</div>
<div class="Home-section">
<span>Already have an account</span>
<%= link_to "Sign-in here", new_session_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%if flash[:error]%>
      <p class="Signin-error"><%=flash[:error]%></p>
    <%end%>
    <%if @current_user%>
      <p class="Home-header">
        <span class="Home-welcome">
          Welcome <%=@current_user.first_name%>,
        </span>
          <span class="Home-signout"><%= link_to "Sign-out" , delete_session_path , method: "delete"%>
        </span>
      </p>
    <%end%>
    <%= yield %>
  </body>
</html>

app/views/todos/_todo-section.html.erb
<section class="TodoSection">
  <div style="display:flex; align-items:baseline;">
  <p class="TodoSection-title"><%=section_title%></p>
  <p class="TodoSection-remaining_count"><%= todos.completed?.count.to_s+" / "+todos.count.to_s%></p>
  </div>
    <% todos.each do |todo_item| %>
    <section class="Todo">
      <%= form_with(url: "/todos/#{todo_item.id}", method: "put") do%>
      <input type="checkbox" name="completed" <%=todo_item.completed? ? "checked" : ""%>
        class="MarkTodo" id="" onclick="this.form.submit()"/>
      <%end%>
      <p class="TodoSection-todotext"
        style="text-decoration:<%=todo_item.completed? ? "line-through" : "none"%>">
        <%= todo_item.todo_text%>
      </p>
      <%if date_flag%>
        <p class="TodoSection-date"><%=todo_item.due_date.to_s(:short)%></p>
      <%end%>
      <span class="delete">
      <%= form_with(url: "/todos/#{todo_item.id}", method: "delete") do%>
      <input type="image" style="height:15px; width:15px" src="delete1.png" alt="delete">
      <%end%>
      </span>
    </section>
    <%end%>
</section>

app/views/todos/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo Management App</title>

  </head>
  <body>
    <main>
      <h1 class="TodoPage-title">My Todo-list</h1>
      <%=form_with(url: "/todos" , method: "post") do%>
        <input class="NewTodo header" type="text" placeholder="What's next?" name="todo_text" id="">
        <input class="Due header" type="date" name="due_date" id="">
        <input class="AddTodo header"type="submit" value="Add">
      <%end%>
      <article>
        <%= render partial: "todo-section", locals: {section_title: "Over Due", todos:@todo.overdue , date_flag: true}%>
        <%= render partial:"todo-section", locals:{section_title:"Due Today",  todos:@todo.due_today , date_flag: false}%>
        <%= render partial:"todo-section", locals:{section_title:"Due Later", todos:@todo.due_later , date_flag: true}%>
      </article>
    </main>
  </body>
</html>

app/views/users/signup.html.erb
<p class="Signup-header">My Todo Manager</p>
<p class="Sign-header">Sign-up</p>
<div class="SignupForm">
  <%=form_with(url: users_path , method: "post") do |form| %>
    <div class="SignupForm-input">
      <p class="SignupForm-label">First Name</p>
      <%=form.text_field :first_name , class: "SignupForm-text"%>
    </div>
   <div class="SignupForm-input">
      <p class="SignupForm-label">Last Name</p>
      <%=form.text_field :last_name, class: "SignupForm-text" %>
   </div>
    <div class="SignupForm-input">
      <p class="SignupForm-label">Email</p>
      <%=form.email_field :email , class: "SignupForm-text"%>
    </div>
    <div class="SignupForm-input">
     <p class="SignupForm-label">Password</p>
     <%=form.password_field :password, class: "SignupForm-text" %>
    </div>
    <div class="SignupForm-input">
     <%= form.submit "Sign-up", class: "SignupForm-submit"%>
    </div>
  <%end%>
</div>